- name: Uploading CentOS 7
  shell: . /etc/profile; acli image.create CentOS container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Linux/CentOS-7-x86_64-DVD-1708.iso

- name: Uploading Windows Server 2016
  shell: . /etc/profile;acli image.create Windows2K16 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2016/en_windows_server_2016_updated_feb_2018_x64_dvd_11636692.iso

- name: Uploading Windows Server 2019
  shell: . /etc/profile;acli image.create Windows2K19 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2019/SW_DVD9_Win_Server_STD_CORE_2019_1809.1_64Bit_English_DC_STD_MLF_X22-02970.iso

- name: Uploading Windows Server 2012 R2
  shell: . /etc/profile; acli image.create Windows2K12 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2012/en_windows_server_2012_r2_vl_with_update_x64_dvd_6052766.iso

- name: Uploading Ubuntu 17.10.1
  shell: . /etc/profile; acli image.create Ubuntu17 container=Images image_type=kIsoImage source_url=http://10.63.25.20/Repo/Mounts/OS/Linux/ubuntu-18.04.3-desktop-amd64.iso

- name: Uploading VirtIO Drivers 
  shell: . /etc/profile; acli image.create VirtIO container=Images image_type=kIsoImage source_url=http://10.63.25.20/Repo/Mounts/Drivers/VirtIO/Nutanix-VirtIO-1.1.3.iso
