---
"pc_ip": "10.63.19.30"
"afs_name": "magicaldrop-fs"
"vg_name": "magicaldrop-vg"
"cvm1": "10.63.18.26"
"cvm2": "10.63.18.27"
"cvm3": "10.63.18.28"
"cvm4": "10.63.18.29"
"host1": "10.63.17.26"
"host2": "10.63.17.27"
"host3": "10.63.17.28"
"host4": "10.63.17.29"
"ipmi1": "10.63.16.26"
"ipmi2": "10.63.16.27"
"ipmi3": "10.63.16.28"
"ipmi4": "10.63.16.29"
