- name: Basic Cluster Setup
  hosts: renegade 
  become: no
  gather_facts: yes 
  vars:
  roles:
  tasks:
    - name: Set EULA
      uri:
       url: https://{{ansible_default_ipv4.address}}:9440/api/nutanix/v1/eulas/accept
       method: POST
       body_format: json
       body: "{{lookup('file','eula1.json')}}"
       user: admin
       password: zxm4=py25PVs:Aw
       force_basic_auth: yes
       return_content: yes
       validate_certs: no

    - name: Disabling Pulse
      uri:
       url: https://{{ansible_default_ipv4.address}}:9440/PrismGateway/services/rest/v1/pulse
       method: PUT
       body_format: json
       body: "{{lookup('file','pulse.json')}}"
       user: admin
       password: zxm4=py25PVs:Aw
       force_basic_auth: yes
       return_content: yes
       validate_certs: no 

    - name: Create Containers
      shell: . /etc/profile; ncli ctr create name="{{ item }}" sp-id=`ncli sp ls | grep Id | grep -v Disk | cut -f 4 -d :`
      loop:
        - ctr1
        - ctr2
        - ctr3

    - name: Uploading Windows Server 2012 R2
      shell: . /etc/profile; acli image.create Windows2K12 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2012/en_windows_server_2012_r2_vl_with_update_x64_dvd_6052766.iso

    - name: Uploading CentOS 7
      shell: . /etc/profile; acli image.create CentOS container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Linux/CentOS-7-x86_64-DVD-1708.iso

    - name: Uploading Windows Server 2016
      shell: . /etc/profile;acli image.create Windows2K16 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2016/en_windows_server_2016_updated_feb_2018_x64_dvd_11636692.iso

    - name: Uploading Windows Server 2019
      shell: . /etc/profile;acli image.create Windows2K19 container=Images image_type=kIsoImage source_url=http://dur-file.sre-labs.nutanix.com/Repo/Mounts/OS/Microsoft/server/2019/SW_DVD9_Win_Server_STD_CORE_2019_1809.1_64Bit_English_DC_STD_MLF_X22-02970.iso

